joint_limits:
  joint_s:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_l:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_e:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_u:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_r:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_b:
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_t:
    has_acceleration_limits: true
    max_acceleration: 5.0