planner:
  ros__parameters:
    plan_solver_plugins: ["POPF"]
    POPF:
      arguments: "-T"
      plugin: "plansys2/POPFPlanSolver"
    TFD:
      plugin: "plansys2/TFDPlanSolver"
executor:
  ros__parameters:
    bt_builder_plugin: "SimpleBTBuilder"
    # bt_builder_plugin: "STNBTBuilder"
